//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public long assetsId { get; set; }
        public string description { get; set; }
        public string link { get; set; }
        public int filmId { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
