//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticketId { get; set; }
        public string state { get; set; }
        public Nullable<int> cost { get; set; }
        public int sessionId { get; set; }
        public int placeId { get; set; }
        public Nullable<long> userId { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
